# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20161213_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='app_label',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
